behaviors:
  SquidGame:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 1e-4
      batch_size: 256
      buffer_size: 32768
      num_epoch: 3
    network_settings:
      # normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
torch_settings:
  device: cpu
